### ISSUE TITLE
Nested loop causing error

### ISSUE THREAD

**Issue by hellonearthis** [bernhardfritz/p8g#15]
If I have a screen/canvas size of greater than 128x128 I get this error.

`Aborted(Cannot enlarge memory arrays to size 30076928 bytes (OOM). Either (1) compile with -sINITIAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -sALLOW_MEMORY_GROWTH which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with -sABORTING_MALLOC=0) `

code example is here: https://observablehq.com/d/bf9eb9659d24d14d#cell-54

happens in both chrome and firefox on win10

Using p8g.js@0.8.0

**Comment by bernhardfritz** [comment]
Thanks for reporting!
I recompiled p8g.js with the `-s ALLOW_MEMORY_GROWTH=1` flag and a few tweaks later I got your example working: https://bernhardfritz.github.io/p8g/examples/noise/
The fix is included in [p8g.js@0.8.1](https://www.npmjs.com/package/p8g.js/v/0.8.1).
Enjoy ☺️

**Comment by hellonearthis** [comment]
Please add a credit to the algorithms original author ひさだん in that example :D And thanks for the fix :D https://twitter.com/hisadan/status/1572219919382753284
